---
kind: pipeline
type: exec
name: Run E2E tests

node:
  os: linux
  arch: amd64

steps:
  - name: test
    commands:
      - go mod download
      - export CI_CATALYST_TEST_IMAGE="${DRONE_REPO}:${DRONE_BUILD_NUMBER}"
      - docker build --tag "$CI_CATALYST_TEST_IMAGE" --build-arg GIT_VERSION="$DRONE_COMMIT_SHA" .
      - 'parallel go test ./test/e2e/* --logtostderr=true -v --image "$CI_CATALYST_TEST_IMAGE" --network "catalyst-test-${DRONE_BUILD_NUMBER}-0{}" ::: $(seq 0 2)'

trigger:
  event:
    - push

---
kind: signature
hmac: 4aec5010241788bb29285134637d5590d9b1199ce5253c36ab6a428ceed9081f

...
