---
kind: pipeline
type: exec
name: Run E2E tests

node:
  os: linux
  arch: amd64

steps:
  - name: test
    commands:
      - go mod download
      - export CI_CATALYST_TEST_IMAGE="${DRONE_REPO}:${DRONE_BUILD_NUMBER}"
      # TODO: implement manifest.yaml auto-updates and dump --no-cache
      - make download
      - docker build --no-cache --tag "$CI_CATALYST_TEST_IMAGE" --build-arg GIT_VERSION="$DRONE_COMMIT_SHA" .
      - 'parallel go test -v ./test/e2e/* --image "$CI_CATALYST_TEST_IMAGE" --network "catalyst-test-${DRONE_BUILD_NUMBER}-0{}" ::: $(seq 0 2)'

trigger:
  event:
    - push

---
kind: signature
hmac: 3c2fc4700afd6d3cc08c6177944fd2e5c66aa8de3bae8a4ba85122ef60becd66
