FROM	ubuntu:20.04

LABEL	maintainer="Amritanshu Varshney <amritanshu+github@livepeer.org>"

RUN	apt update && apt install -yqq \
	ca-certificates \
	musl \
	python3 \
	ffmpeg \
	nodejs \
	&& rm -rf /var/lib/apt/lists/*

ADD ./bin ./usr/bin

EXPOSE	1935	4242	8080	8889/udp

CMD	["/usr/bin/MistController", "-c", "/etc/livepeer/catalyst.json"]
