FROM ubuntu:20.04 AS mistbuild

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y build-essential cmake git

ARG MIST_COMMIT=changeme

WORKDIR /box

RUN git clone https://github.com/ddvtech/mistserver.git /mistserver \
  && cd /mistserver \
  && git checkout $MIST_COMMIT

ADD Makefile Makefile
RUN make mistserver BUILD_SHARED_LIBS=yes

FROM ubuntu:20.04
COPY --from=mistbuild /box/bin/* /usr/bin
COPY --from=mistbuild /box/lib/* /usr/lib
ENTRYPOINT ["MistController"]
