#!/bin/bash

set -euo pipefail

if [[ $* == *-j* ]]; then
    echo '{
  "desc": "Livepeer-packaged RabbitMQ",
  "name": "Livepeer RabbitMQ",
  "optional": {}
}'
    exit 0
fi

set -x RABBITMQ_NODENAME=rabbit@localhost
set -x RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_stream advertised_host localhost"

cat > /etc/rabbitmq/rabbitmq.conf <<EOF
  default_vhost = livepeer
  loopback_users = none
EOF
rabbitmq-plugins enable --offline rabbitmq_stream
rabbitmq-plugins enable --offline rabbitmq_management
bash <<EOF &
  until rabbitmqadmin --vhost=livepeer declare exchange name=lp_golivepeer_metadata type=topic && \
        rabbitmqadmin --vhost=livepeer declare exchange name=webhook_default_exchange type=topic && \
        rabbitmqadmin --vhost=livepeer declare exchange name=lp_mist_api_connector type=topic && \
        rabbitmqadmin --vhost=livepeer declare exchange name=lp_global_replication type=topic; do
    sleep 1;
  done
EOF

exec rabbitmq-server
