#!/bin/bash

set -euo pipefail

if [[ $* == *-j* ]]; then
    echo '{
  "name": "Livepeer Victoria Metrics",
  "desc": "Livepeer-in-a-Box packaged Victoria Metrics. Comes with some built-in scrape configs for dev.",
  "friendly": "Livepeer-in-a-Box packaged Victoria Metrics",
  "optional": {
    "envflag.enable": {
      "name": "envflag.enable",
      "help": "Whether to enable reading flags from environment variables additionally to command line. Command line flag values have priority over values from environment vars. Flags are read only from command line if this flag is not set. See https://docs.victoriametrics.com/#environment-variables for more details",
      "option": "-envflag.enable",
      "default": "true"
    },
    "envflag.prefix": {
      "name": "envflag.prefix",
      "help": "Prefix for environment variables if -envflag.enable is set",
      "option": "-envflag.prefix",
      "default": "VM_",
      "type": "str"
    },
    "promscrape.config": {
      "name": "promscrape.config",
      "help": "Location of promscape.config file",
      "option": "-promscrape.config",
      "default": "./config/scrape_config.yaml",
      "type": "str"
    }
  },
  "version": "0.0.1"
}'
    exit 0
fi

exec lp-victoria-metrics "$@"
