#!/bin/bash

set -euo pipefail

if [[ $* == *-j* ]]; then
    echo '{
  "desc": "Livepeer-packaged nginx",
  "name": "Livepeer nginx",
  "optional": {}
}'
    exit 0
fi

cat > /etc/nginx/nginx.conf << EOF
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
daemon off;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;
    client_max_body_size 10G;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    access_log /proc/1/fd/2;
    error_log /proc/1/fd/2;

    gzip on;

    server {
        listen       8888;
        listen       4443 ssl;
        ssl_certificate     /tls/tls.crt;
        ssl_certificate_key /tls/tls.key;
        server_name  _;
        absolute_redirect off;
        
        location /mist/hls/ {
            proxy_pass http://localhost:8081/hls/;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_read_timeout 600s;
            proxy_set_header Host \$host;
            proxy_set_header X-Mst-Path "\$scheme://\$host:8888/mist";
        }

        location /mist/ {
            proxy_pass http://localhost:8080/;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_read_timeout 600s;
            proxy_set_header Host \$host;
            proxy_set_header X-Mst-Path "\$scheme://\$host:\$server_port/mist";
        }

        proxy_set_header Host \$host:\$server_port;
        proxy_set_header X-Forwarded-For \$remote_addr;

        location /hls/ {
            proxy_pass http://127.0.0.1:8989;
        }

        location /webrtc/ {
            proxy_pass http://127.0.0.1:8989;
        }

        location /api/data/ {
            proxy_pass http://127.0.0.1:3080;
        }

        location /data/ {
            proxy_pass http://127.0.0.1:3080;
        }

        location /os-vod/ {
            proxy_pass http://127.0.0.1:9000;
        }

        location /os-catalyst-vod/ {
            proxy_pass http://127.0.0.1:9000;
        }

        location /os-private/ {
            proxy_pass http://127.0.0.1:9000;
        }

        location /os-recordings/ {
            proxy_pass http://127.0.0.1:9000;
        }

        location / {
            proxy_pass http://127.0.0.1:3004;
        }
    }
}
EOF

exec nginx
