#!/bin/bash

set -euo pipefail

if [[ $* == *-j* ]]; then
    echo '{
  "desc": "Livepeer-packaged Coturn",
  "name": "Livepeer Coturn",
  "optional": {}
}'
    exit 0
fi

exec turnserver \
  --min-port 40000 \
  --max-port 40100 \
  -u livepeer:livepeer \
  -r localhost \
  --no-tls \
  --no-dtls \
  --lt-cred-mech \
  -X 192.168.230.130 \
  --allow-loopback-peers \
  --cli-password livepeer
