#!/bin/bash

set -euo pipefail

if [[ $* == *-j* ]]; then
    echo '{
  "desc": "Livepeer-packaged Minio",
  "name": "Livepeer Minio",
  "optional": {}
}'
    exit 0
fi

# Loop
bash <<EOF &
  until mc alias set minio-server http://localhost:9000 admin password \
  && mc mb minio-server/os-vod --ignore-existing \
  && mc mb minio-server/os-catalyst-vod --ignore-existing \
  && mc mb minio-server/os-private --ignore-existing \
  && mc mb minio-server/os-recordings --ignore-existing \
  && mc mb minio-server/os-recordings-backup --ignore-existing \
  && mc anonymous set download minio-server/os-vod \
  && mc anonymous set download minio-server/os-catalyst-vod \
  && mc anonymous set download minio-server/os-private \
  && mc anonymous set download minio-server/os-recordings \
  && mc anonymous set download minio-server/os-recordings-backup \
  ; do \
    sleep 1;
  done
EOF

MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password exec minio server /data/minio --console-address ":9001" --address "127.0.0.1:9000"
